<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.0" name="joined_together_in_a_tilemap-Sheet" tilewidth="8" tileheight="8" tilecount="364" columns="28">
 <editorsettings>
  <export target="tilemap.json" format="json"/>
 </editorsettings>
 <image source="../gfx/tile_sheet.png" trans="2ce8f4" width="224" height="104"/>
 <tile id="8" type="Collision"/>
 <tile id="9" type="Kill"/>
 <tile id="36" type="Collision"/>
 <tile id="37" type="Kill"/>
 <tile id="50" type="Collision"/>
 <tile id="53" type="Kill"/>
 <tile id="54" type="Collision"/>
 <tile id="64" type="Collision"/>
 <tile id="65" type="Kill"/>
 <tile id="78" type="Collision"/>
 <tile id="81" type="Kill"/>
 <tile id="82" type="Collision"/>
 <tile id="83" type="Kill"/>
 <tile id="106" type="Collision"/>
 <tile id="107" type="Kill"/>
 <tile id="109" type="Kill"/>
 <tile id="110" type="Collision"/>
 <tile id="111" type="Kill"/>
 <tile id="133" type="Kill"/>
 <tile id="134" type="Collision"/>
 <tile id="137" type="Kill"/>
 <tile id="138" type="Collision"/>
 <tile id="140" type="Kill"/>
 <tile id="141" type="Kill"/>
 <tile id="161" type="Kill"/>
 <tile id="162" type="Collision"/>
 <tile id="163" type="Kill"/>
 <tile id="166" type="Collision"/>
 <tile id="189" type="Kill"/>
 <tile id="190" type="Collision"/>
 <tile id="192" type="Kill"/>
 <tile id="193" type="Collision"/>
 <tile id="194" type="Collision"/>
 <tile id="195" type="Kill"/>
 <tile id="196" type="Collision"/>
 <tile id="198" type="Collision"/>
 <tile id="199" type="Collision"/>
 <tile id="200" type="Collision"/>
 <tile id="201" type="Collision"/>
 <tile id="202" type="Collision"/>
 <tile id="203" type="Collision"/>
 <tile id="217" type="Kill"/>
 <tile id="218" type="Collision"/>
 <tile id="220" type="Kill"/>
 <tile id="221" type="Collision"/>
 <tile id="222" type="Collision"/>
 <tile id="223" type="Win"/>
 <tile id="224" type="Collision"/>
 <tile id="226" type="Collision"/>
 <tile id="227" type="Collision"/>
 <tile id="228" type="Collision"/>
 <tile id="229" type="Collision"/>
 <tile id="230" type="Collision"/>
 <tile id="231" type="Collision"/>
 <tile id="246" type="Collision"/>
 <tile id="247" type="Kill"/>
 <tile id="248" type="Kill"/>
 <tile id="249" type="Collision"/>
 <tile id="250" type="Collision"/>
 <tile id="251" type="Win"/>
 <tile id="252" type="Collision"/>
 <tile id="255" type="Kill"/>
 <tile id="256" type="Kill"/>
 <tile id="257" type="Kill"/>
 <tile id="274" type="Collision"/>
 <tile id="275" type="Kill"/>
 <tile id="276" type="Kill"/>
 <tile id="277" type="Collision"/>
 <tile id="278" type="Collision"/>
 <tile id="279" type="Win"/>
 <tile id="280" type="Collision"/>
 <tile id="281" type="Collision"/>
 <tile id="283" type="Kill"/>
 <tile id="284" type="Kill"/>
 <tile id="285" type="Kill"/>
 <tile id="287" type="Collision"/>
 <tile id="288" type="Collision"/>
 <tile id="300" type="Collision"/>
 <tile id="301" type="Kill"/>
 <tile id="302" type="Collision"/>
 <tile id="303" type="Kill"/>
 <tile id="308" type="Collision"/>
 <tile id="309" type="Collision"/>
 <tile id="310" type="Collision"/>
 <tile id="315" type="Collision"/>
 <tile id="316" type="Collision"/>
 <tile id="317" type="Collision"/>
 <tile id="318" type="Collision"/>
 <tile id="327" type="Collision"/>
 <tile id="328" type="Collision"/>
 <tile id="329" type="Kill"/>
 <tile id="330" type="Collision"/>
 <tile id="331" type="Kill"/>
 <tile id="354" type="Collision"/>
 <tile id="355" type="Collision"/>
</tileset>
