<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.1" name="level" tilewidth="8" tileheight="8" tilecount="324" columns="18">
 <image source="level.png" width="144" height="144"/>
 <tile id="0" type="WALL"/>
 <tile id="1" type="WALL"/>
 <tile id="2" type="WALL"/>
 <tile id="3" type="WALL"/>
 <tile id="4" type="WALL"/>
 <tile id="5" type="WALL"/>
 <tile id="6" type="WALL"/>
 <tile id="7" type="WALL"/>
 <tile id="8" type="WALL"/>
 <tile id="9" type="WALL"/>
 <tile id="10" type="WALL"/>
 <tile id="11" type="WALL"/>
 <tile id="12" type="WALL"/>
 <tile id="13" type="WALL"/>
 <tile id="14" type="WALL"/>
 <tile id="15" type="WALL"/>
 <tile id="16" type="WALL"/>
 <tile id="17" type="WALL"/>
 <tile id="18" type="WALL"/>
 <tile id="19" type="WALL"/>
 <tile id="20" type="WALL"/>
 <tile id="21" type="WALL"/>
 <tile id="22" type="WALL"/>
 <tile id="23" type="WALL"/>
 <tile id="24" type="WALL"/>
 <tile id="25" type="WALL"/>
 <tile id="26" type="WALL"/>
 <tile id="27" type="WALL"/>
 <tile id="28" type="WALL"/>
 <tile id="29" type="WALL"/>
 <tile id="30" type="WALL"/>
 <tile id="31" type="WALL"/>
 <tile id="32" type="WALL"/>
 <tile id="33" type="WALL"/>
 <tile id="34" type="WALL"/>
 <tile id="35" type="WALL"/>
 <tile id="36" type="WALL"/>
 <tile id="37" type="WALL"/>
 <tile id="38" type="FLOOR"/>
 <tile id="39" type="FLOOR"/>
 <tile id="40" type="FLOOR"/>
 <tile id="41" type="FLOOR"/>
 <tile id="42" type="FLOOR"/>
 <tile id="43" type="FLOOR"/>
 <tile id="44" type="FLOOR"/>
 <tile id="45" type="FLOOR"/>
 <tile id="46" type="FLOOR"/>
 <tile id="47" type="FLOOR"/>
 <tile id="48" type="FLOOR"/>
 <tile id="49" type="FLOOR"/>
 <tile id="50" type="FLOOR"/>
 <tile id="51" type="FLOOR"/>
 <tile id="52" type="WALL"/>
 <tile id="53" type="WALL"/>
 <tile id="54" type="WALL"/>
 <tile id="55" type="WALL"/>
 <tile id="56" type="FLOOR"/>
 <tile id="57" type="FLOOR"/>
 <tile id="58" type="FLOOR"/>
 <tile id="59" type="FLOOR"/>
 <tile id="60" type="FLOOR"/>
 <tile id="61" type="FLOOR"/>
 <tile id="62" type="FLOOR"/>
 <tile id="63" type="FLOOR"/>
 <tile id="64" type="FLOOR"/>
 <tile id="65" type="FLOOR"/>
 <tile id="66" type="FLOOR"/>
 <tile id="67" type="FLOOR"/>
 <tile id="68" type="FLOOR"/>
 <tile id="69" type="FLOOR"/>
 <tile id="70" type="WALL"/>
 <tile id="71" type="WALL"/>
 <tile id="72" type="WALL"/>
 <tile id="73" type="WALL"/>
 <tile id="74" type="WALL"/>
 <tile id="75" type="WALL"/>
 <tile id="76" type="WALL"/>
 <tile id="77" type="WALL"/>
 <tile id="78" type="WALL"/>
 <tile id="79" type="WALL"/>
 <tile id="80" type="WALL"/>
 <tile id="81" type="WALL"/>
 <tile id="82" type="WALL"/>
 <tile id="83" type="WALL"/>
 <tile id="84" type="WALL"/>
 <tile id="85" type="WALL"/>
 <tile id="86" type="WALL"/>
 <tile id="87" type="WALL"/>
 <tile id="88" type="WALL"/>
 <tile id="89" type="WALL"/>
 <tile id="90" type="WALL"/>
 <tile id="91" type="WALL"/>
 <tile id="92" type="WALL"/>
 <tile id="93" type="WALL"/>
 <tile id="94" type="WALL"/>
 <tile id="95" type="WALL"/>
 <tile id="96" type="WALL"/>
 <tile id="97" type="WALL"/>
 <tile id="98" type="WALL"/>
 <tile id="99" type="WALL"/>
 <tile id="100" type="WALL"/>
 <tile id="101" type="WALL"/>
 <tile id="102" type="WALL"/>
 <tile id="103" type="WALL"/>
 <tile id="104" type="WALL"/>
 <tile id="105" type="WALL"/>
 <tile id="106" type="WALL"/>
 <tile id="107" type="WALL"/>
 <tile id="108" type="WALL"/>
 <tile id="109" type="WALL"/>
 <tile id="110" type="WALL"/>
 <tile id="111" type="WALL"/>
 <tile id="112" type="WALL"/>
 <tile id="113" type="WALL"/>
 <tile id="114" type="WALL"/>
 <tile id="115" type="WALL"/>
 <tile id="116" type="WALL"/>
 <tile id="117" type="WALL"/>
 <tile id="118" type="WALL"/>
 <tile id="119" type="WALL"/>
 <tile id="126" type="WALL"/>
 <tile id="127" type="WALL"/>
 <tile id="128" type="WALL"/>
 <tile id="129" type="WALL"/>
 <tile id="130" type="WALL"/>
 <tile id="131" type="WALL"/>
 <tile id="132" type="WALL"/>
 <tile id="133" type="WALL"/>
 <tile id="134" type="WALL"/>
 <tile id="135" type="WALL"/>
 <tile id="136" type="WALL"/>
 <tile id="137" type="WALL"/>
 <tile id="144" type="WALL"/>
 <tile id="145" type="WALL"/>
 <tile id="146" type="WALL"/>
 <tile id="147" type="WALL"/>
 <tile id="148" type="WALL"/>
 <tile id="149" type="WALL"/>
 <tile id="150" type="WALL"/>
 <tile id="151" type="WALL"/>
 <tile id="152" type="WALL"/>
 <tile id="153" type="WALL"/>
 <tile id="162" type="WALL"/>
 <tile id="163" type="WALL"/>
 <tile id="164" type="WALL"/>
 <tile id="165" type="WALL"/>
 <tile id="166" type="WALL"/>
 <tile id="167" type="WALL"/>
 <tile id="168" type="WALL"/>
 <tile id="169" type="WALL"/>
 <tile id="170" type="WALL"/>
 <tile id="171" type="WALL"/>
 <tile id="180" type="WALL"/>
 <tile id="181" type="WALL"/>
 <tile id="182" type="WALL"/>
 <tile id="183" type="WALL"/>
 <tile id="184" type="WALL"/>
 <tile id="185" type="WALL"/>
 <tile id="186" type="WALL"/>
 <tile id="187" type="WALL"/>
 <tile id="188" type="WALL"/>
 <tile id="189" type="WALL"/>
 <tile id="198" type="WALL"/>
 <tile id="199" type="WALL"/>
 <tile id="200" type="WALL"/>
 <tile id="201" type="WALL"/>
 <tile id="202" type="WALL"/>
 <tile id="203" type="WALL"/>
 <tile id="204" type="WALL"/>
 <tile id="205" type="WALL"/>
 <tile id="206" type="WALL"/>
 <tile id="207" type="WALL"/>
</tileset>
