#!/bin/bash


rm -rf target/export
mkdir target/export

cp -r html target/export

cd target/export || exit

cargo build --release
arm-none-eabi-objcopy -O binary ../thumbv4t-none-eabi/release/gmtk22 "Hyperspace Roll.gba"
gbafix -tHYPERSPACE -cHYLL -mGC "Hyperspace Roll.gba" 

cp "Hyperspace Roll.gba" html/game.gba

(cd html || return && zip -r ../html.zip .)
