[package]
name = "tapir-sounds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22"
env_logger = "0.10"
im = "15"
petgraph = "0.6"
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
